### ISSUE TITLE
Ubuntu 15.04 : Compile errors from Swig

### ISSUE THREAD

**Issue by bharathpatil** [3dtof/voxelsdk#1]
On Behald of Alex : 
While trying to build the Voxel-SDK library -

In Ubuntu 15.04 (SWIG 2.0.5 and g++ 4.9.2 I am getting compile errors from both SWIG (when it encounters a construct llike this:
Foo<bar<baz>>
it can be fixed by adding a space:
Foo<bar<baz> >)
and from g++ (being unable to generate a default constructor)

**Comment by larrylisky** [comment]
I had the same issue compiling Voxel SDK 0.6.0.  I found the issue to be related to the fact that I had both python 2.7 and python 3.4 installed on my system.  To fix it, run 'cmake-gui ..' from the build directory and change all python reference to python 2.7.

**Comment by hlprasu** [comment]
One permanent fix to handle this situation is to change

FIND_PACKAGE(PythonLibs)

to

FIND_PACKAGE(PythonLibs 2.7 EXACT REQUIRED)

in Voxel/SWIG/CMakeLists.txt

However, you'll have to start the build fresh with a blank build directory. Or else, it will pick cached variables and try to use to 3.x version again. This applies to 16.04 and possibly newer versions of Ubuntu too.
