### ISSUE TITLE
The smallest depth camera

### ISSUE THREAD

**Issue by abencomo** [3dtof/voxelsdk#109]
What is the smallest depth camera that voxelsdk is known to support?

**Comment by gadiyar** [comment]
If you meant smallest in terms of resolution, then in voxelsdk we support all TI 3DTOF chipsets. All of these can be configured to use smaller ROIs than the maximum.

**Comment by abencomo** [comment]
No, I meant in term of hardware, like this [one](http://www.baslerweb.com/en/products/cameras/area-scan-cameras/dart/daa1280-54uc#dimensions):

**Comment by gadiyar** [comment]
The only one that you can commercially order at this time is this one:
http://www.ti.com/tool/OPT8241-CDK-EVM

The others are reference designs that TI does not currently sell.
