### ISSUE TITLE
CameraSystemConfigTest: Allow not having a default profile in EEPROM

### ISSUE THREAD

**Issue by gadiyar** [3dtof/voxelsdk#129]
If a profile stored in EEPROM has been set as the default, we need a way to unset the default flag - this is needed so that we can start up purely with a profile stored in a conf file, instead of one stored in the EEPROM. Otherwise, the profile in the EEPROM always wins.

**Comment by suramyag1** [comment]
Fixed using https://github.com/3dtof/voxelsdk/commit/b06d582500c0540de39a78ec6529b61b20967442
