### ISSUE TITLE
make install Failed 

### ISSUE THREAD

**Issue by jkablan** [3dtof/voxelsdk#142]
I am attempting to build / install commit ffb7df8b4136f3ac8793ebe696731c527bdc5a1c 

I am able to get the source to build 

when i run "make install" I get the following error. 

`-- Up-to-date: /usr/local/include/voxel-0.6.11/Filter/DarkPixFilter.h
-- Up-to-date: /usr/local/include/voxel-0.6.11/Filter/DenoiseFilter.h
CMake Error at Voxel/cmake_install.cmake:112 (file):
  file INSTALL cannot find
  "/home/idl/software/voxelsdk/Voxel/Filter/Flypixfilter.h".
Call Stack (most recent call first):
  cmake_install.cmake:37 (include)

Makefile:71: recipe for target 'install' failed
make: *** [install] Error 1
`

When I look for files with Flypix in the name in the source directory I find the following 

`find .. | grep Flypix
../build/Voxel/CMakeFiles/voxel.dir/Filter/FlypixFilter.cpp.o
../Voxel/Filter/FlypixFilter.h
../Voxel/Filter/FlypixFilter.cpp
`
There's a difference in capitalization between the filename the make script is looking for (Flypixfilter.h) and the source (FlypixFilter.h)

Thanks

**Comment by suramyag1** [comment]
Fixed using https://github.com/3dtof/voxelsdk/commit/11872fdfe613fb45226d0cbee0246ff3cae23d9a
