### ISSUE TITLE
Voxel sdk installation [Warning! PATH too long installer unable to modify PATH!"]

### ISSUE THREAD

**Issue by torabzadeh1370** [3dtof/voxelsdk#145]
The installation completes despite showing this warning. How can I fix this warning and does it affect running the program? I selected "add path to all user accounts" in the installation.

**Comment by suramyag1** [comment]
Hi, 

Since the setup is unable to modify the system PATH variable, you need to do this manually. The installation is successful, but system PATH is not updated. Add these to the system path:

```
C:\Program Files\PCL 1.7.2\bin
C:\Program Files\PCL 1.7.2\3rdParty\VTK\bin
C:\Qt\Qt5.4.0\5.4\msvc2013_win64\bin
<path_to_voxel_sdk_folder>\build\bin
<path_to_voxel_sdk_folder>\build\lib
```

**Comment by suramyag1** [comment]
Closing this issue
