### ISSUE TITLE
WARNING: CameraSystem: No depth camera library found or loaded.

### ISSUE THREAD

**Issue by pans0ul** [3dtof/voxelsdk#156]
Ive built project and could run the VoxelCLI.. with:  https://github.com/3dtof/voxelsdk/wiki/Installation-on-Linux

My os is Ubuntu 14.04LTS ,I ran VoxelCLI ,but it can not connete the depth camera .why? 
if the problem is No depth camera library found or loaded, How do I solve this problem? 
please help me ,thanks a lot!

the picture is as follow:
![2018-07-06_144116](https://user-images.githubusercontent.com/35412241/42363612-ddc9bada-812a-11e8-8cdf-2cde429ac1f0.jpg)

**Comment by pans0ul** [comment]
please help me

**Comment by suramyag1** [comment]
Hi! 

Have you updated the PATH variables correctly? Use these variables if you've built voxelsdk:
https://github.com/3dtof/voxelsdk/wiki/Build-from-source-on-Linux#running-from-source

**Comment by suramyag1** [comment]
@pans0ul 

Did this resolve the issue? Can I close this thread?

**Comment by pans0ul** [comment]
@suramyag1   sure, thanks!
