### ISSUE TITLE
APPCRASH when voxelsdk-examples DepthCapture was excuted in win7 

### ISSUE THREAD

**Issue by jarodlee0304** [3dtof/voxelsdk#157]
Hello,
I excuted the voxelsdk-examples DepthCapture in win7 and App was crashed.
Software
OS: win7 Service Pack 1
Cmake (cmake-gui) Version: 3.12.0
PCL-1.7.2-AllInOne-msvc2015-win64
Visual studio 14 2015 Win64
DemoApplications: DepthCapture
Hardware
OPT8241-CDK-EVM
Environment variables were all setup according to requirements.
When I used cmake-gui to build project, Configuring and Generating were both done.
Command in Windows terminal: cmake --build . --target ALL_BUILD --config Release, no error but 126 warning.
Executed App DepthCapture in win7 terminal: DepthCapture.exe -v 0x0451 -p 0x9105 -s 12019461200050 -f filename.bin -n 100 -t raw_processed
![1](https://user-images.githubusercontent.com/33558035/42746664-8667fda4-890b-11e8-9f71-b7ab32405499.JPG)
APPCRASH ISSUE
![2](https://user-images.githubusercontent.com/33558035/42746682-9ec3fbbe-890b-11e8-9633-45f3f366ead7.JPG)
Appcrash always happen when codes run to
depthCamera->registerCallback(DepthCamera::FRAME_RAW_FRAME_PROCESSED, [&](DepthCamera &dc, const Frame &frame, DepthCamera::FrameType c) {
      const ToFRawFrame *d = dynamic_cast<const ToFRawFrame *>(&frame); ...
Looking forward to reply!

**Comment by suramyag1** [comment]
Hi @jarodlee0304, 

It seems that you built a new version of the SDK, but the VOXEL_SDK_PATH is still set to D:\Program Files (x86)\Voxel SDK .. 
Please change that and try running it again. 

Suramya

**Comment by jarodlee0304** [comment]
Hi Suramya,
I installed the Voxel.SDK-0.6.10-win64.exe in win7 OS directly, not built SDK. So VOXEL_SDK_PATH was set to D:\Program Files (x86)\Voxel SDK 0.6.10

**Comment by suramyag1** [comment]
@jarodlee0304 

I'm sorry, i thought you built VoxelSDK as well. This could be a compatibility issue, then. VoxelSDK was built using VS2013. 
If you want to use VS2015, you may need to build the SDK yourself.

**Comment by jarodlee0304** [comment]
Hi Suramya,
When I installed the release version Voxel.SDK-0.6.10-win64.exe in win7 OS, chose PCL 1.7.2 and Qt 5.8 winrt_x64_msvc2015 for it already.

**Comment by suramyag1** [comment]
@jarodlee0304 

The release has been compiled using VS2013, so specifying msvc2015 will not work. 

If you want a VS2015 release, please use the older release (https://github.com/3dtof/voxelsdk/releases/download/v0.6.9/Voxel.SDK-0.6.9-msvc2015-win64.exe)
