### ISSUE TITLE
Issue of "Build from voxelsdk 0.6.11 source on Win10 64-bit" process

### ISSUE THREAD

**Issue by CJHsiehinleda** [3dtof/voxelsdk#160]
Hi
I encountered a compiled error during building process.
Error message during compile with VS2015 64-bit and voxelsdk 0.6.11 (from releases site) is shown below
![image](https://user-images.githubusercontent.com/37663816/43254213-79fac84e-90f9-11e8-8fc6-4aceb62ddbf5.png)
How to solve it? 

Before compiling, I installed
1. PCL 1.8.0
2. Doxygen 1.8.9.1
3. swingwin 3.0.12
4. graphviz  2.38
5. Qt 5.6.3 for 64-bit
And set PATH as
![image](https://user-images.githubusercontent.com/37663816/43254322-b7654b28-90f9-11e8-9f6a-d37b04aaf5e0.png)
Do I get the wrong configuration?

**Comment by suramyag1** [comment]
Hi @CJHsiehinleda 

Can you try building in the Release mode? 

It seems that you already have Voxel SDK 0.6.10 installed. I don't think this is needed to build 0.6.11 (you can remove those lines from the path, although it wouldn't make a difference). 

Suramya

**Comment by CJHsiehinleda** [comment]
After switch to Release mode, I finally can compile. 
Thanks! @suramyag1
