### ISSUE TITLE
Can VoxelSDk work on Raspberry Pi 3 linux 【not Ubuntu MATE】

### ISSUE THREAD

**Issue by pointcloud-ai** [3dtof/voxelsdk#166]
How can i build VoxelSDK on Raspberry Pi 3 linux ? 
Ubuntu MATE on Raspberry Pi  is slow.

**Comment by suramyag1** [comment]
Hi @pointcloud-ai, 

Attached are the instructions to run voxelsdk on Raspbian.
[SettingUp_RaspberryPi](https://github.com/3dtof/voxelsdk/files/2532863/SettingUp_RaspberryPi.txt)

Although the instructions have been verified, errors, if any, won't be supported.
