### ISSUE TITLE
Temperature calibration about VoxelVader

### ISSUE THREAD

**Issue by adgiczone** [3dtof/voxelsdk#167]
Hello, I am doing temperature calibration. I got the coefficients for tsensor and tillum and found no difference before and after setting the coefficients.
The parameters which I set are calib_prec(1), tillum_calib, tsensor_calib, coeff_illum, coeff_sensor and disable_temp_corr is false.
What have I forgotten? Why is it invalid after setting these parameters?

**Comment by suramyag1** [comment]
Hi @adgiczone ,
Please post to https://e2e.ti.com for questions related to the sensor. 

Suramya
