### ISSUE TITLE
prebuild VoxelSDK install on ubuntu16.04

### ISSUE THREAD

**Issue by robust-lu** [3dtof/voxelsdk#171]
I follow the instructions of [https://github.com/3dtof/voxelsdk/wiki/Installation-on-Linux] to install VoxelSDK 0.6.10 on ubuntu16.04. When I run sudo dpkg -i libvoxel*.deb libti3dtof*.deb, it shows:

dpkg: dependency problems prevent configuration of libti3dtof-dev:
 libti3dtof-dev depends on libvoxel-dev (>= 0.6.10); however:
  Package libvoxel-dev is not installed.

but there is no libvoxel-dev package in 0.6.10, how to solve it?

**Comment by suramyag1** [comment]
@robust-lu 

I've updated the release. It should work now.

**Comment by robust-lu** [comment]
OK, it works.

**Comment by arenas7307979** [comment]
follow the instructions of [https://github.com/3dtof/voxelsdk/wiki/Installation-on-Linux] to install VoxelSDK 0.6.10 on **ubuntu18.04**. When I run sudo dpkg -i libvoxel*.deb libti3dtof*.deb, it shows:

dpkg: dependency problems prevent configuration of libti3dtof-dev:
libti3dtof-dev depends on libvoxel-dev (>= 0.6.10); however:
Package libvoxel-dev is not installed.

but there is no libvoxel-dev package in 0.6.10, how to solve it?
