### ISSUE TITLE
DepthCapture example code issue

### ISSUE THREAD

**Issue by amjad14** [3dtof/voxelsdk#22]
After installing the binary for Voxel SDK and building DepthCapture.cpp, the executable doesn't perform any action.

**Comment by Jc-Seo** [comment]
> I figured out the order.
> 
> for row = 1:240
> for col= 1:320
> Depthimage( row , col ) = A(k); // A is the float vector with the stream of data from binary file
> k=k+1;
> end
> end

Can I ask you how did you read .bin file generated from DepthCapture.cpp?
I want to read bin file and pass it to opencv Mat
