### ISSUE TITLE
Voxelsdk for arm version

### ISSUE THREAD

**Issue by userkenny** [3dtof/voxelsdk#35]
Hi sir,

I'm compiling voxelsdk to raspberry pi for arm based platform (kernel version 4.1.9+ & gcc version (Raspbian 4.7.3-11+rpi1) 4.7.3, & g++ version (Raspbian 4.9.2-10) 4.9.2 )). after make command, I found error below. Any suggestion? thx. & lt also looks the libpcl-all is not able to install onto RPI system. not sure is it related to the erroe or not. see below...

pi@raspberrypi ~/voxelsdk/build $ make
[  1%] Building CXX object Voxel/CMakeFiles/voxel.dir/Device.cpp.o
c++: error: unrecognized command line option '-msse2'
make[2]: *** [Voxel/CMakeFiles/voxel.dir/Device.cpp.o] Error 1
make[1]: *** [Voxel/CMakeFiles/voxel.dir/all] Error 2
make: *** [all] Error 2

BR Kenny

**Comment by userkenny** [comment]
Hi sir,

I compiled the voxelsdk w/o problem but while I run the executable in App folder. I found below message. not sure which camera libray is not loaded? The VoxelCLI has same message output. thank you.

pi@ubuntu:~/voxelsdk/build/App$ ./SimpleVoxelViewer
WARNING: CameraSystem: No depth camera library found or loaded.
SimplePCLViewer: Could not find a compatible device.
pi@ubuntu:~/voxelsdk/build/App$

**Comment by userkenny** [comment]
Never mind it, I forget set set 3 variables paths.
but it now looks no depth data observed in CLI or Simple viewer.

**Comment by larrylisky** [comment]
@userkenny:  What ARM processor were you running?  Were there any error messages from the VoxelCLI or SimpleViewer?

**Comment by userkenny** [comment]
I'm looking into cross compile alternative for my raspberrypi (RPI) under Ubuntu 14.04 64bits environment. It is because If I directly compiled on RPI, it did not have big ram to compile voxelsdk till the end & throw out of memory error message in the middle. 
But I failed to cross compiled for RPI under several cmake-gui setting trials. Any ideas to cross compile for an embed arm system, like RPI? thx.

Regards, Kenny

**Comment by larrylisky** [comment]
Direct compiling due to ram limitation, try turn on swap.  When I built voxelsdk for Pandaboard I had to turn on 2G+ swap.

I haven't tried cross-compiling, your challenge may be coming  from the dependencies, such as swig3.0, pcl, etc, which voxel-sdk needs access to at least the headers.

I found this link which may be helpful, if you haven't seen it already.  http://www.openframeworks.cc/setup/raspberrypi/Raspberry-Pi-Cross-compiling-guide.html

Make sure cmake is using the right CC, etc... so it's pointing to the cross tool.

**Comment by userkenny** [comment]
Hi Larrylisky,
I choice to enlarge the swap space as 2G bytes. but I found below error while directly make compiling in RPI. any idea?

[ 75%] Building CXX object TI3DToF/CMakeFiles/ti3dtof.dir/ToFCrossTalkFilter.cpp.o
Linking CXX shared library libti3dtof.so
[ 75%] Built target ti3dtof
[ 76%] Building CXX object TI3DToF/boards/HaddockCDK/CMakeFiles/haddockcdk.dir/HaddockCDKCamera.cpp.o
[ 77%] Building CXX object TI3DToF/boards/HaddockCDK/CMakeFiles/haddockcdk.dir/HaddockCDKCameraFactory.cpp.o
Linking CXX shared library ../../libhaddockcdk.so
[ 77%] Built target haddockcdk
[ 78%] Building CXX object TI3DToF/boards/TintinCDK/CMakeFiles/tintincdk.dir/TintinCDKCamera.cpp.o
[ 79%] Building CXX object TI3DToF/boards/TintinCDK/CMakeFiles/tintincdk.dir/TintinCDKCameraFactory.cpp.o
[ 80%] Building CXX object TI3DToF/boards/TintinCDK/CMakeFiles/tintincdk.dir/TintinCDKDownloaderFactory.cpp.o
[ 81%] Building CXX object TI3DToF/boards/TintinCDK/CMakeFiles/tintincdk.dir/TintinEEPROMDownloader.cpp.o
/home/pi/voxelsdk/TI3DToF/boards/TintinCDK/TintinEEPROMDownloader.cpp: In member function 'virtual bool Voxel::TI::TintinEEPROMDownloader::_configureForDownload()':
/home/pi/voxelsdk/TI3DToF/boards/TintinCDK/TintinEEPROMDownloader.cpp:47:36: error: converting to 'const SlaveAddressToByteMap {aka const std::unordered_map<unsigned int, unsigned int, std::hash<unsigned int>, std::equal_to<unsigned int>, std::allocator<std::pair<const unsigned int, unsigned int> > >}' from initializer list would use explicit constructor 'std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = unsigned int; _Tp = unsigned int; _Hash = std::hash<unsigned int>; _Pred = std::equal_to<unsigned int>; _Alloc = std::allocator<std::pair<const unsigned int, unsigned int> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<unsigned int>; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<unsigned int>; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const unsigned int, unsigned int> >]'
     VoxelXUProgrammer p({}, _device);
                                    ^
make[2]: *** [TI3DToF/boards/TintinCDK/CMakeFiles/tintincdk.dir/TintinEEPROMDownloader.cpp.o] Error 1
make[1]: *** [TI3DToF/boards/TintinCDK/CMakeFiles/tintincdk.dir/all] Error 2
make: *** [all] Error 2

**Comment by larrylisky** [comment]
I've seen this before.  Sometimes you just have to run 'make' again without deleting anything in the build directory, and make will continue and complete.  This cause is likely memory limitation.   Turn swap on perhaps to a larger size may help also.

**Comment by larrylisky** [comment]
Here is a link to prebuilts for voxelsdk and pcl for armhf.

https://github.com/3dtof/prebuilt

**Comment by hlprasu** [comment]
This is really cool! Thanks, Larry!

~ Prasad Bhat

**Comment by ashokbugude** [comment]
@userkenny  Can I please know which variable paths have you setup in one of your above comments which reads as follows
![voxel](https://cloud.githubusercontent.com/assets/10016848/19190368/cd9165f2-8cba-11e6-8dc0-f2151ab327f2.png)

I too am getting CameraSystem: No depth camera library found or loaded. error

**Comment by userkenny** [comment]
Hi,

I'm sorry & I'm kind of long time away from that message.


2016-10-07 5:52 GMT-07:00 ashokbugude <notifications@github.com>:
