### ISSUE TITLE
Compile error that need fixed.

### ISSUE THREAD

**Issue by myme5261314** [3dtof/voxelsdk#36]
There's a compile error while the ``make all`` command for voxelsdk under my environment as below.
> Ubuntu 14.04x64
> g++/gcc v4.9.2
And the issue was the same one described by this [post](http://stackoverflow.com/questions/26947704/implicit-conversion-failure-from-initializer-list)
I've wrote a fix solution you might want to check, if it won't lead into other new issues, please consider merge it in.

**Comment by hlprasu** [comment]
Thanks! We have included this fix now in code.

**Comment by hlprasu** [comment]
Note: This fix is only for gcc 4.9.2 to work. This does not affect later gcc >= 5, part of Ubuntu 15.10
