### ISSUE TITLE
Example code request - calibrated point cloud

### ISSUE THREAD

**Issue by larrylisky** [3dtof/voxelsdk#38]
Is there voxelsdk C++ example showing how to get calibration point cloud? The current example does not seem to provide calibrated point cloud (selecting the profile that has the proper calibration?).

**Comment by hlprasu** [comment]
Could you please specify which device you are using? TintinCDK?

On 6 November 2015 at 20:19, Larry Li <notifications@github.com> wrote:

> Is there voxelsdk C++ example showing how to get calibration point cloud?
> The current example does not seem to provide calibrated point cloud
> (selecting the profile that has the proper calibration?).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3dtof/voxelsdk/issues/38>.
>



-- 
~ Prasad Bhat

**Comment by gadiyar** [comment]
I think it's common for all devices, right? The examples code (VoxelCLI or SimpleVoxelViewer for example) for users does not show how to set a profile. I think this is only available in the VoxelViewer code right now.

**Comment by larrylisky** [comment]
Correct, we need an example that works for all devices, as long as the calibration profiles exist on the CDK hardware.

**Comment by hlprasu** [comment]
If you have not created any new profiles, then pre-installed default
profile will be used.

If you have created a new profile which is made default then it will be
used in Voxel CLI or Simple Voxel Viewer.

From the question, I understand that the default profile is not calibrated
appropriately.

@Larry: Could you please the messages shown when you run VoxelCLI or
SimpleVoxelViewer?

On 6 November 2015 at 22:28, gadiyar <notifications@github.com> wrote:

> I think it's common for all devices, right? The examples code (VoxelCLI or
> SimpleVoxelViewer for example) for users does not show how to set a
> profile. I think this is only available in the VoxelViewer code right now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3dtof/voxelsdk/issues/38#issuecomment-154471928>.
>



-- 
~ Prasad Bhat

**Comment by larrylisky** [comment]
@hlprasu:  The question was referring to how to access pre-calibrated profile stored on the CDK.  After lens calibration, the MetrilusHWProfile is stored to the CDK and that's the one I want to use.  How do I load that profile by name (or by ID) during execution?

**Comment by hlprasu** [comment]
In SDK, you can use depthCamera->setCameraProfile(id) to set the desired camera profile.

You can use depthCamera->getCameraProfileNames() to get a map object of all valid IDs to names. Note that IDs are unique and names need not be.
