### ISSUE TITLE
install libpcl-all does not install libpcl-visualization.so

### ISSUE THREAD

**Issue by larrylisky** [3dtof/voxelsdk#39]
I noticed in my latest Ubuntu install of pcl following the below command:

```
  sudo apt-get install libpcl-all
```

it does not install libpcl-visualization.so needed b voxelsdk.  I had to download pcl-1.7.2 directly from PCL  Github and build it to have PCL properly installed.  Please verify this and update the wiki.

**Comment by hlprasu** [comment]
Which version Ubuntu are you using?

On 6 November 2015 at 20:23, Larry Li <notifications@github.com> wrote:

> I noticed in my latest Ubuntu install of pcl following the below command:
>
>   sudo apt-get install libpcl-all
>
> it does not install libpcl-visualization.so needed b voxelsdk. I had to
> download pcl-1.7.2 directly from PCL Github and build it to have PCL
> properly installed. Please verify this and update the wiki.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3dtof/voxelsdk/issues/39>.
>



-- 
~ Prasad Bhat

**Comment by larrylisky** [comment]
14.04

**Comment by larrylisky** [comment]
Also I think PCL master branch has moved onto version 1.8.

**Comment by hlprasu** [comment]
I just checked again that libpcl-all should work fine. It in-turn installs
libpcl-visualization-1.7-dev which creates the required
libpcl_visualization.so.

Could you please check whether 'apt-get install libpcl-all' was successful
for your installation?

Is this issue for 32-bit/64-bit Intel/AMD architecture or for ARM
architecture?


On 6 November 2015 at 22:29, Larry Li <notifications@github.com> wrote:

> Also I think PCL master branch has moved onto version 1.8.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3dtof/voxelsdk/issues/39#issuecomment-154472220>.
>



-- 
~ Prasad Bhat

**Comment by larrylisky** [comment]
Him. Didn't work for me. Will try again. 

Larry

**Comment by hlprasu** [comment]
Is this issue still there?

**Comment by gadiyar** [comment]
Closing - no further action. Please reopen if this is still an issue.

**Comment by joerowelll** [comment]
I am getting the same problem, the apt version of pcl doesnt install visualization. Is there a way around this without building from source?

**Comment by gadiyar** [comment]
Are you on a recent version of Ubuntu? This project is quite old and later PCL versions might have changed.

I would recommend building from source.

Also, do you have one of the depth cameras that this project supports? They're quite rare to come by these days.
