### ISSUE TITLE
Amplitude control

### ISSUE THREAD

**Issue by larrylisky** [3dtof/voxelsdk#40]
How do I control using Voxel SDK the TinTin CDK's illumination?

**Comment by gadiyar** [comment]
Use the DepthCamera::set API - same API for setting all parameters.

depthCamera->set('illum_power', value) should work I think.

**Comment by larrylisky** [comment]
Closed.  Use 'illum_power_percentage', which for TinTin CDK goes from 48U to 100U.  The unsigned type is important.  Make sure the 'set' function returns 1 to notify success.
