### ISSUE TITLE
 VoxelCLI: add command to set a profile.

### ISSUE THREAD

**Issue by gadiyar** [3dtof/voxelsdk#50]
VoxelCLI has most features needed to work with a camera. However it is missing the ability to set a camera profile.

This would be useful to allow switching to profiles other than the default

**Comment by hlprasu** [comment]
Yes, agreed.

On 11 December 2015 at 12:12, gadiyar <notifications@github.com> wrote:

> VoxelCLI has most features needed to work with a camera. However it is
> missing the ability to set a camera profile.
>
> This would be useful to allow switching to profiles other than the default
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3dtof/voxelsdk/issues/50>.
>



-- 
~ Prasad Bhat

**Comment by gadiyar** [comment]
Added by https://github.com/3dtof/voxelsdk/commit/1b10e8b12285c0ba698a218edce4f3d46a53c95a
