### ISSUE TITLE
how to do the burn in the parameter in .conf to flash?

### ISSUE THREAD

**Issue by kevinliu-ez** [3dtof/voxelsdk#56]
Hello, 
2 questions:
1. we had done the calibration and setup many parameters in .conf.
could you let us know how to call Realtek API and download those parameters into the Flash?
(it seems your existed interface is I2C but Realtek use SPI
2. what parameter defined in the .conf is related to temperature calibration?
tnks alot

**Comment by gadiyar** [comment]
This needs to be implemented by someone, as we do not have access to their API.
The board file needs to implement APIs to store a binary blob to the EEPROM and be able to read it 
back. See this commit for an implementation on the TintinCDK:

https://github.com/3dtof/voxelsdk/commit/3119a48b95c1210063c481699ee5a7990ab831ee

The tsensor_calib, tillum_calib, coeff_illum and coeff_sensor, and calib_prec parameters are the ones used for temperature compensation in the OPT9221.
