### ISSUE TITLE
Is it important to enable De-aliasing? how much deviation do you estimate?

### ISSUE THREAD

**Issue by kevinliu-ez** [3dtof/voxelsdk#57]
We are conducting serious calibration tests. we wondering whether it is important to conduct such feature or not. tnks!

**Comment by bharathpatil** [comment]
Kevin,

De-aliasing does not improve the accuracy. It only improves the unambiguous range of the system. For example, with 40MHz, a range of 3.75m and with 60MHz a range of 2.5m can be achieved. But with the combination, a range of 7.5m can be achieved (equivalent frequency of GCD(40,60)=20MHz). Please refer to the dealiasing section in the OPT9221 datasheet for more details.

Regards
Bharath
