### ISSUE TITLE
Phase Non-Linearity Correction-- we try to develop our owned code but not using voxelviewer...

### ISSUE THREAD

**Issue by kevinliu-ez** [3dtof/voxelsdk#59]
we try to develop our owned code but not using voxelviewer. how to prepare the LUT to be the same as you use in your default LUT? (16 points in a phase???)

**Comment by bharathpatil** [comment]
Kevin,

You got it right! It is just 16-bits of signed phase offset per pixel. Starting from 0,0 and ending with 240,320 in row major form.

Regards
Bharath
