### ISSUE TITLE
how much deviation if not doing temperature compensation?

### ISSUE THREAD

**Issue by kevinliu-ez** [3dtof/voxelsdk#60]
We are conducting serious calibration tests. we wondering whether it is important to conduct such feature or not. how much deviation do you expect? tnks!

**Comment by bharathpatil** [comment]
Kevin,

 Typically, for high illumination power circuits, this is a must. In general, where the illumination path has large delays (>2ns) due to the use of large MOSFETS, Errors of the order of 1ft can be expected without temperature calibration in the form of hardware or software.

Regards
Bharath

**Comment by kevinliu-ez** [comment]
Dear Bharath:
Thanks a lot for your answers!
It helps!

Bharath Patil <notifications@github.com> 於 2016年2月1日 星期一寫道：

> Kevin,
>
> Typically, for high illumination power circuits, this is a must. In
> general, where the illumination path has large delays (>2ns) due to the use
> of large MOSFETS, Errors of the order of 1ft can be expected without
> temperature calibration in the form of hardware or software.
>
> Regards
> Bharath
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3dtof/voxelsdk/issues/60#issuecomment-177604338>.
>


-- 

Kevin Liu，Ph.D
GM, eZimage Technology Inc
易積生活科技
0919377901
