### ISSUE TITLE
Default filter bank to boost point-cloud quality.

### ISSUE THREAD

**Issue by byfron** [3dtof/voxelsdk#62]
The windows original TI voxel viewer achieves a very nice point-cloud quality (outlier free) out-of-the-box probably due to a nice toolchain of filters that are set by default. It'd be nice to include an example/test where the point cloud is already pre-processed by such filter bank. I'm doing some tests right now with TintinCDK so I'll be happy to contribute if I succeed

**Comment by hlprasu** [comment]
By default, there are no filters applied. However, a default camera profile
is applied which sets various calibrations. The default camera profile is
applied whether you use SDK or viewer.

SDK has API to select camera profile while viewer has a menu to select the
same.

~ Prasad Bhat

**Comment by byfron** [comment]
Hi Prasad, thanks for your answer. So after playing around I realized the is the amplitude threshold the parameter that was removing the outliers in the windows gui, so no filtering indeed.
