### ISSUE TITLE
Applying filters on recorded data

### ISSUE THREAD

**Issue by byfron** [3dtof/voxelsdk#63]
It seems that applying filters to pre-recorded VXL raw sequences is not straightforward. The FrameStreamReader class does not implement this functionality as far as I know.

**Comment by hlprasu** [comment]
Yes, true. It is not supported.

~ Prasad Bhat

**Comment by byfron** [comment]
It'd be really useful to be able to process raw vxl data as if there was a "virtual" camera so that all the regular camera parameters as well as filters can be applied.

**Comment by hlprasu** [comment]
Noted. Filters are possible to implement though not in the plan yet.

Parameters will be practically not possible as they are meant to influence
the initial raw data itself and not subsequent processing.

On 2 February 2016 at 16:40, byfron <notifications@github.com> wrote:

> It'd be really useful to be able to process raw vxl data as if there was a
> "virtual" camera so that all the regular camera parameters as well as
> filters can be applied.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3dtof/voxelsdk/issues/63#issuecomment-178513997>.
>



-- 
~ Prasad Bhat

**Comment by byfron** [comment]
Although I assume certain parameters like illumination power thresholds could be applied in pre-recorded raw data right?. At least the windows Voxel viewer gui can do this. 

Thanks anyway and looking forward to those improvements.

**Comment by hlprasu** [comment]
In order to apply the parameters such as illumination power, we will need
to fully simulate the sensor board itself which is not the target of Voxel
SDK. The VXL format is a playback format and not really a simulation format.

~ Prasad Bhat
