### ISSUE TITLE
Voxel SDK 0.6.0 does not work with OPT8320 CDK

### ISSUE THREAD

**Issue by larrylisky** [3dtof/voxelsdk#66]
Here is the error message:

ERROR: USBIO: Control transfer issue: Status 0
ERROR: VoxelUSBProgrammer: Could not read register for address 0x2d5
ERROR: VoxelProgrammerBase: Could not read register for address 0x2d05
ERROR: DepthCamera: Failed to update value for parameter 'mix_volt'
ERROR: USBIO: Control transfer issue: Status 0
ERROR: VoxelUSBProgrammer: Could not read register for address 0x2d5
ERROR: VoxelProgrammerBase: Could not read register for address 0x2d05
ERROR: DepthCamera: Failed to update value for parameter 'mix_volt'
ERROR: USBIO: Control transfer issue: Status 0
ERROR: VoxelUSBProgrammer: Could not read register for address 0x2d5
ERROR: VoxelProgrammerBase: Could not read register for address 0x2d05
ERROR: DepthCamera: Failed to update value for parameter 'mix_volt'
ERROR: CameraSystem: Could not refresh parameters for CalculusCDKCamera(0::0451:9107::Serial_No._Placeholder).
Profile MetrilusLongRangenot found.
_dealiasedPhaseMask = 0, _dealiasedPhaseMaskInPhaseOffset = 0

**Comment by gadiyar** [comment]
I've pushed some updates. Could you please pull again and check if the current master branch works for you?
