### ISSUE TITLE
How to start voxel sdk programming with vs2013?

### ISSUE THREAD

**Issue by iammeizu** [3dtof/voxelsdk#67]
I am a newcomer to voxel sdk, and I have already installed voxel sdk6.0 in my pc. I have run VoxelCLI.exe successfully.
What should I do next ? 
How to build a test project?
How to configure my vs 2013?
Do I need a TI‘s OPT8241-CDK-EVM ?

Thank you in advance !

**Comment by hlprasu** [comment]
Please have a look at
https://github.com/3dtof/voxelsdk/wiki/Voxel-SDK-User-Guide

On 30 March 2016 at 08:01, iammeizu <notifications@github.com> wrote:

> I am a newcomer to voxel sdk, and I have already installed voxel sdk6.0 in
> my pc. I have run VoxelCLI.exe successfully.
> What should I do next ?
> How to build a test project?
> How to configure my vs 2013?
> Do I need a TI‘s OPT8241-CDK-EVM ?
>
> Thank you in advance !
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/3dtof/voxelsdk/issues/67>
>



-- 
~ Prasad Bhat

**Comment by iammeizu** [comment]
I am using 64-bit win10, so I installed Voxelsdk not build from source on windows.
Dose this mean I must install voxelsdk again(from source)? 
Thank you again!

**Comment by hlprasu** [comment]
No. Not necessary. However, please install all the prerequisites mentioned
in  https://github.com/3dtof/voxelsdk/wiki/Build-from-source-on-Windows in
order to compile the example given in
https://github.com/3dtof/voxelsdk/wiki/Voxel-SDK-User-Guide

On 30 March 2016 at 08:35, iammeizu <notifications@github.com> wrote:

> I am using 64-bit win10, so I installed Voxelsdk not build from source on
> windows.
> Dose this mean I must install voxelsdk again(from source)?
> Thank you again!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/3dtof/voxelsdk/issues/67#issuecomment-203222421>
>



-- 
~ Prasad Bhat
