### ISSUE TITLE
How to start voxel SDK programming with BCB6 in Win7 win32 environment

### ISSUE THREAD

**Issue by AtiiTed** [3dtof/voxelsdk#70]
1 . I use OPT8241-CDK-EVM   , Self-development program 
2. I need to install software and steps .
3. Examples of programs BCB6 ?

**Comment by hlprasu** [comment]
Could you please see the wiki page? https://github.com/3dtof/voxelsdk/wiki

~ Prasad Bhat

**Comment by AtiiTed** [comment]
I have question about "Build from source on Windows" , i use voxel.lib and 3dtof.lib development BCB6 program,  I think comfirm CMake ,Git ,Doxygen,GarphViz and SWIG sofeware need to install ?  

https://github.com/3dtof/voxelsdk/wiki/Build-from-source-on-Windows

**Comment by gadiyar** [comment]
Sorry, I'm afraid we don't support BCB6 - you're on your own there.
