### ISSUE TITLE
windows build instruction error

### ISSUE THREAD

**Issue by sravanM** [3dtof/voxelsdk#72]
Some clarifications to the wiki instructions that might help other people:

cyapi.h and cyapi.lib should be in voxel-sdk/Voxel/CyAPI and not voxel-sdk/Voxel/

It's unclear whether QT is a requirement, but here's the link to the version you guys are using:
http://download.qt.io/archive/qt/5.4/5.4.0/

Visual studio 2013 express:
https://www.microsoft.com/en-us/download/details.aspx?id=48131

**Comment by hlprasu** [comment]
1. Fixed wiki with correct path for CyAPI copying.
2. Qt is a not needed (it might be implicitly used by PCL whenever present
but not necessary).
3. Visual studio 2013 or better is fine. No need to restrict to 2013 alone.

On 27 April 2016 at 11:36, Sravan Mettupalli <notifications@github.com>
wrote:

> Some clarifications to the wiki instructions that might help other people:
>
> cyapi.h and cyapi.lib should be in voxel-sdk/Voxel/CyAPI and not
> voxel-sdk/Voxel/
>
> It's unclear whether QT is a requirement, but here's the link to the
> version you guys are using:
> http://download.qt.io/archive/qt/5.4/5.4.0/
>
> Visual studio 2013 express:
> https://www.microsoft.com/en-us/download/details.aspx?id=48131
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/3dtof/voxelsdk/issues/72>
>



-- 
~ Prasad Bhat

**Comment by sravanM** [comment]
re: 2: It complained about QT for me so so perhaps there is some option to not build something that is using it?

3: I think the Boost library in that version of PCL is specific to Visual studio 12 (lib64-msvc-12), it didn't work for me out of the box with 15, but I suppose I could have built boost myself

**Comment by gadiyar** [comment]
Also, for VS2013‎, make sure Update 4 or later is installed.


From: Sravan Mettupalli
Sent: Wednesday, April 27, 2016 03:33
To: 3dtof/voxelsdk
Reply To: 3dtof/voxelsdk
Subject: Re: [3dtof/voxelsdk] windows build instruction error (#72)



re: 2: It complained about QT for me so so perhaps there is some option to not build something that is using it?

3: I think the Boost library in that version of PCL is specific to Visual studio 12 (lib64-msvc-12), it didn't work for me out of the box with 15, but I suppose I could have built boost myself
