### ISSUE TITLE
Complie error of OPT8320 FX2

### ISSUE THREAD

**Issue by jorjin-image** [3dtof/voxelsdk#77]
Hi,

I already installed SDCC 2.9.0 and GNU Make 3.81 to complied OPT8320 FX2 source code, but I encountered a problem as below:
![1](https://cloud.githubusercontent.com/assets/13991796/15353530/1a04e634-1d1c-11e6-8f97-8b4b01da7474.png)

How can I solve it? Thanks

**Comment by gadiyar** [comment]
We do not support the OPT8320 FX2 source on this forum - I do notice the released code is missing the prototype for i2c_write_nostop().

Please send me an email at gadiyar (at) ti.com and I'll notify you of updated FX2 source codes.
