### ISSUE TITLE
Voxel SDK User Guide example problem

### ISSUE THREAD

**Issue by jorjin-image** [3dtof/voxelsdk#78]
Hi,
In Voxel SDK User Guide, there is one example “DepthCapture”.
I build this program successfully.
I run the “DepthCapture.exe” with command :
DepthCapture.exe -v 0451 -p 9107 -s 0001 -f testimg -n 1 -t raw

It showed : No valid device found for the specified VID:PID:serialnumber
How can I solve it? Thanks.

**Comment by gadiyar** [comment]
Please confirm if the "SimpleVoxelViewer" or "VoxelCLI" programs from the SDK or the VoxelViewer program distributed separately are able to see the camera.

Please confirm that the VOXEL_SDK_PATH environment variable is set correctly.

**Comment by jorjin-image** [comment]
The OPT8320 CDK can show images in Voxel Viewer-0.7.16.
But the "SimpleVoxelViewer" and "VoxelCLI" programs have some problems.

In \voxelsdk\App :
Run SimpleVoxelViewer.cmd : It flashed a windows.
![2016-05-19_102439](https://cloud.githubusercontent.com/assets/13991796/15380804/25059890-1dac-11e6-83d5-454c1499ba32.png)
Run VoxelCLIStart.cmd :
![2016-05-19_102755](https://cloud.githubusercontent.com/assets/13991796/15380820/636a7b8c-1dac-11e6-8616-56fe05835c4e.png)

In \voxelsdk\build\bin :
Run SimpleVoxelViewer.exe : 
![2016-05-19_103830](https://cloud.githubusercontent.com/assets/13991796/15380973/ddaae1a6-1dad-11e6-90b6-813cf767e2d3.png)
Run VoxelCLI.exe : It shows "The procedure entry point could not be located"
![2016-05-19_103138](https://cloud.githubusercontent.com/assets/13991796/15380871/e9225024-1dac-11e6-859b-167565931453.png)

And this is my VOXEL_SDK_PATH environment variable.
![2016-05-19_104044](https://cloud.githubusercontent.com/assets/13991796/15381005/2e6f6f26-1dae-11e6-9ce0-c78d4926834f.png)

**Comment by hlprasu** [comment]
Try C:\Users\Jorjin\voxelsdk\build for VOXEL_SDK_PATH

~ Prasad Bhat

**Comment by jorjin-image** [comment]
I changed VOXEL_SDK_PATH to C:\Users\Jorjin\voxelsdk\build.
But it's not working.

**Comment by jorjin-image** [comment]
Hello,
I changed VOXEL_SDK_PATH to another voxelsdk(C:\Program Files\Voxel SDK 0.6.3).
C:\Program Files\Voxel SDK 0.6.3 is from https://github.com/3dtof/voxelsdk/wiki/Installation-on-Windows.
C:\Users\Jorjin\voxelsdk\build is from https://github.com/3dtof/voxelsdk/wiki/Build-from-source-on-Windows.
And the "SimpleVoxelViewer" or "VoxelCLI" programs can work.

I used USBDeview to find out VID, PID and serial number.
![2016-05-19_154938](https://cloud.githubusercontent.com/assets/13991796/15386261/66b2957c-1dd9-11e6-9fde-cee627f61c4a.png)
Then I run the “DepthCapture.exe” with command :
DepthCapture.exe -v 0451 -p 9107 -s Serial_No._Placeholder -f testimg -n 1 -t raw
But  the “DepthCapture.exe” can't work.
![2016-05-19_154415](https://cloud.githubusercontent.com/assets/13991796/15386132/92dba6ee-1dd8-11e6-8cd7-5369c4dcef22.png)

**Comment by hlprasu** [comment]
From the last screenshot, it seems like it has run properly and saved one
frame.

~ Prasad Bhat

**Comment by jorjin-image** [comment]
I got the data like following.
![2016-05-19_163528](https://cloud.githubusercontent.com/assets/13991796/15387428/b904b8b8-1ddf-11e6-8fe6-c780a11f222b.png)
How can I open it?

**Comment by padi-jagadeesh** [comment]
Hi,
The file didn't get written as (in the CLI) there is an error saying 
"ERROR:HardwareSerializer: Invalid Config data in Hardware."
I encountered the similar error lately. I checked all the config files which are fine.
Is there anything missing??

I have written my own script in linux which is working fine but this example is well written with more functionality and it would be helpful if it works. 


![screenshot at 2016-12-01 09_18_54_github](https://cloud.githubusercontent.com/assets/21159437/21295370/b32633bc-c579-11e6-9d04-c09824834780.png)

**Comment by gadiyar** [comment]
@padi-jagadeesh This is just a warning saying there is no pre-calibrated profile saved in the EEPROM.
You can ignore this warning for now.

What is the actual problem you are facing?

**Comment by padi-jagadeesh** [comment]
@gadiyar 
Ok.....But, I'm unable to open the dump file......I thought it is binary encoding, so used ".txt"......but not worked....
Is there any format for dumpfile that i need to follow???

**Comment by gadiyar** [comment]
Data captured using the DepthCapture.cpp example are just raw binary data. Please read them in your program as raw binary.
Or use python+numpy ( np.fromfile() ) or similar functions in Matlab.

You can refer to the DepthCapture.cpp source code to see the format in which the data is written, and decode accordingly.

**Comment by padi-jagadeesh** [comment]
@gadiyar 
Thank you....I have written a C file and read the data now......

If someone needs the decoding format, make use of https://e2e.ti.com/support/sensor/optical_sensors/f/989/t/503049
bin file encoding contains device _id(4 bytes) and Timestamp(8 bytes) in the starting of each frame........consider them while decoding

**Comment by gadiyar** [comment]
Closing, please reopen a new issue if this is still a problem.
