### ISSUE TITLE
USB: Dropping a frame because of slow forward pipeline.

### ISSUE THREAD

**Issue by christophk86** [3dtof/voxelsdk#79]
I get following warning messages in the sample application VoxelCLI:
_USB: Dropping a frame because of slow forward pipeline._
The warning message comes 2-3 times every second. So that I cannot use the VoxelCLI shell for configuration.
Is it possible to turn off this warning?

What is the reason for this warning? I set up the 20fps. If I set the framerat to 30fps the warning turns off.

Thanks in advance.

**Comment by flyflyfly001** [comment]
@christophk86 Hello! Have you solved this problem? I got the same problem with you.
