### ISSUE TITLE
Voxel SDK v0.6.3 installation is missing HardwareSerializer.h

### ISSUE THREAD

**Issue by larrylisky** [3dtof/voxelsdk#81]
The build-all-deb.sh generated DEB packages does not install HardwareSerializer.h to /usr/include/voxel, and this leads to build error.  If I copy it there manually build works fine.

**Comment by gadiyar** [comment]
Fixed with https://github.com/3dtof/voxelsdk/commit/25a5b95be4c65e46433fbc578fe4323d444bca00
