### ISSUE TITLE
Downloader class not working with HaddockCDK

### ISSUE THREAD

**Issue by AlexanderSilvaB** [3dtof/voxelsdk#82]
Hi,

I'm trying to use the class Downloader with HaddockCDK but everytime I call the download method and it internally calls _usbIO->controlTransfer, this method always return false and I'm presented with the error "USBIO: Control transfer issue.".

Do you know if there's something I can do solve this?
Thank you very much in advance.

**Comment by gadiyar** [comment]
Hi Alexander,

We do not support Downloader for Haddock CDK in the Voxel SDK.

For Haddock CDK, firmware upgrades can be done using the 3D Explorer software that originally shipped with the Haddock CDK board.

- Anand

**Comment by gadiyar** [comment]
For further support on the Haddock CDK not related to the Voxel SDK, please reach out to us at ti-3dtof (at) list.ti.com.

**Comment by AlexanderSilvaB** [comment]
Hi @gadiyar , thank you very much!

It's possible to get the firmware source code to do modifications?  If yes, how can I get it?

Thank you!

**Comment by gadiyar** [comment]
Hi @AlexanderSilvaB,

I'm afraid not - we do not share the firmware source and it is not updated frequently.

**Comment by AlexanderSilvaB** [comment]
Oh, it's ok. Thank you @gadiyar! :)
