### ISSUE TITLE
Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)

### ISSUE THREAD

**Issue by ashokbugude** [3dtof/voxelsdk#88]
I am trying to install voxel in linux, but get below error messages, pls help resolve the issues

zayyon@zayyon-Lenovo-ideapad-300-15ISK:~/Downloads/voxelsdk-0.6.3$ sudo ./build-all-deb.sh major
Linux
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindSWIG.cmake:75 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  Voxel/SWIG/CMakeLists.txt:5 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/zayyon/Downloads/voxelsdk-0.6.3/build/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target 'clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
CPack Error: Cannot find CPack config file: "CPackConfig-*.cmake"
dpkg: error processing archive *major*.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 *major*.deb
cp: cannot stat '*major*.deb': No such file or directory
tar: *.deb: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

**Comment by larrylisky** [comment]
You seemed to be missing swig3 in your Linux box. Please follow the instruction on the Voxel SDK wiki page and install all prerequisites before compiling. 

-Larry

**Comment by ashokbugude** [comment]
Thanks.
