### ISSUE TITLE
Skeleton Tracking with voxelsdk

### ISSUE THREAD

**Issue by ashokbugude** [3dtof/voxelsdk#95]
Can I please know how to implement skeleton tracking using voxelsdk ?

**Comment by larrylisky** [comment]
Look for open source application that uses point cloud and OpenNI/NITE.  You can probably leverage those libraries.  voxelsdk outputs the same types of depth/amplitude and 3d data as Kinect.

**Comment by ashokbugude** [comment]
Hi Thanks for your response. 
 The pcl(point cloud library) has openi/nite viewer which works fine with kinect v1 and v2.

I am trying to use voxel for TI sensors which does not work with openi/nite as they work only with kinect.
 Could I please know how to use voxel or any other library to implement skeleton tracking with Ti's TOF sensors

**Comment by larrylisky** [comment]
@ashokbugude:  You may want to try this:

YouTube:
[https://www.youtube.com/watch?v=FmXbS5DkSsw](url)
Code:
[https://github.com/Norman0406/OpenSkeletonFitting](url)

Look in the OpenSFInput folder, and follow the InputKinect class example to create a new input class InputVoxel by deriving from the Input class.

**Comment by SneakyLuke88** [comment]
Here is another solution, base on TI sensors, with fully compatible with OpenNI V1.5 and 2.2
https://www.youtube.com/watch?v=_qrw2AhSthI

**Comment by SneakyLuke88** [comment]
You could use this 
http://www.lips-hci.com/products/sdk/

**Comment by gadiyar** [comment]
Closing, this is not a voxelsdk issue.
